### ISSUE TITLE
templating in mails factory - document behaviour

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#135]
Just a reminder not to forget: This is working only because the name of the template i.e `cds_librarian_footer.html` is different than the default defined [here](https://github.com/inveniosoftware/invenio-app-ils/pull/928/files#diff-1eb6fa33c5d713c03754783b9e137036R82). @KonstantinaStoikou @kprzerwa we might need to document that somewhere because it can lead to nasty errors in the future 😓

_Originally posted by @zzacharo in https://github.com/CERNDocumentServer/cds-books/pull/131/files_

the feature of overwriting the email templates should be documented in details, including the emails creation factories

**Comment by ntarocco** [comment]
I am not sure I understand this, ping @zzacharo. In order to override a mail template in CDS-ILS, you will have to:
1. create your own template html file
2. override one the following config var: `ILS_CIRCULATION_MAIL_TEMPLATES`, `ILS_DOCUMENT_REQUEST_MAIL_TEMPLATES`, `ILS_ILL_MAIL_TEMPLATES`.

We will need more details in the ticket to understand what is the issue.
