### ISSUE TITLE
Add proxy endpoint for e-items

### ISSUE THREAD

**Issue by ntarocco** [CERNDocumentServer/cds-ils#162]
At CERN, e-items can contain link that are not freely accessible, for example for ebooks that have been purchased by the library. The librarian will always mark such ebooks as `open_access: False`.

There are 2 types of closed access e-items:
1. the URL is accessible as anonymous, but then the provider/vendor will require login in their website
2. the URL requires a reverse proxy before (while will require CERN login). The link to the e-book should be prefixed withg the EzProxy URL. The URL will be marked as `login_required: True`

## Implementation

- [x] REST APIs: on `login_required: True`, when serializing back the response, a new field `login_required_url` should contain the final URL with EzProxy
- [x] UI: change every UI cmp where the link with `login_required` is shown to use the new field `login_required_url` as value instead of the original.
- [x] Adapt the migration script to set the right `open_access` and `login_required` fields for URLs.

## Example

Record metadata
```
url: {
    value: "https://myprotectedurl.com?id=...",
    login_required: True
}
```

REST API response
```
url: {
    value: "https://myprotectedurl.com?id=...", 
    login_required: True,
    login_required_url: "https://ezproxy.cern.ch?url=<encoded https://myprotectedurl.com?id=..."
}
```

Link
```
<a href="https://ezproxy.cern.ch?url=<encoded https://myprotectedurl.com?id=...">https://myprotectedurl.com?id=...</a>
```

**Comment by ntarocco** [comment]
See wip: https://github.com/CERNDocumentServer/cds-ils/pull/169

**Comment by ntarocco** [comment]
Implements https://github.com/CERNDocumentServer/cds-ils/issues/31

**Comment by jrcastro2** [comment]
## Migration 
This table determines when a link should be migrated as restricted or not.
rules \ links | EBL | Safari | Local files |  rest of links(e-items)
--------------- | ----- | --------- | --------- | --------
 "Open Access" in 8564_y | Restricted (by default) | Restricted (by default) | not taken into account(files restriction) | Not restricted
"Open Access" in 0247_q | Restricted (by default) | Restricted (by default) | not taken into account(files restriction)  | Not restricted
"Open Access" in 536__r* | Restricted (by default) | Restricted (by default) | not taken into account(files restriction)  | Not restricted

 **536__r***: This one is globally it means that applies to all e-items (except for EBL, Safari and local files) present in the record, while 8564_y and 0247_q only apply to one concrete e-item.
* 
**Note**: EzProxy links should always be restricted otherwise we raise an exception.
