### ISSUE TITLE
importer - CDS provider failing

### ISSUE THREAD

**Issue by jrcastro2** [CERNDocumentServer/cds-ils#248]
### Description
When importing records using CDS as provider it's failing.

### Steps to reproduce
1. Execute the importer command `cds-ils importer import-from-file -p cds <file.xml>`.

### Result
It displays an error.

### Expected result
Should import records correctly without the error.

### Screeenshots
![image](https://user-images.githubusercontent.com/15194802/100470451-953ffd00-30d8-11eb-89f3-838d2756acb5.png)

**Comment by KonstantinaStoikou** [comment]
The error is caused because the record in the `cds-example.xml` file is a multivolume which is excluded in the [model](https://github.com/CERNDocumentServer/cds-ils/blob/06528d6151a3a1a34b2395af781605543cd99a03/cds_ils/importer/providers/cds/models/book.py#L29), so there is no model to match the record and it fallbacks to the [default model](https://github.com/inveniosoftware/dojson/blob/master/dojson/contrib/marc21/model.py) which doesn't have a `do` attribute.
