### ISSUE TITLE
Search on strings with accent, apostrophe, ampersand

### ISSUE THREAD

**Issue by agentilb** [CERNDocumentServer/cds-ils#543]
**Describe the bug**
If you search on a string where there is accents or apostrophes, the query doesn't work if you don't put the accent. 

**To Reproduce**
<img width="1192" alt="Screenshot 2021-06-08 at 15 03 20" src="https://user-images.githubusercontent.com/12181904/121189854-cb6dee80-c86a-11eb-852a-3eb2d6e78f0f.png">
<img width="1192" alt="Screenshot 2021-06-08 at 15 03 30" src="https://user-images.githubusercontent.com/12181904/121189878-d0cb3900-c86a-11eb-9545-36c6268880e2.png">
<img width="1192" alt="Screenshot 2021-06-08 at 15 03 59" src="https://user-images.githubusercontent.com/12181904/121189899-d45ec000-c86a-11eb-8628-2b14b4e7b385.png">

Ex: `frühwirth` finds many results, but `fruhwirth` finds only one record. 

**Expected behavior**
The query should work with or without the accents and the apostrophe

**Comment by salomerohr** [comment]
Due to this issue, it also causes an issue when matching in the importer. It is not the same behavior with or without accents:
https://catalogue.library.cern/backoffice/importer/task/285   
https://catalogue.library.cern/backoffice/importer/task/286    

The files are attached.
[moshe-flato-with-accent.txt](https://github.com/CERNDocumentServer/cds-ils/files/8059250/moshe-flato-with-accent.txt)
[moshe-flato-without-accent.txt](https://github.com/CERNDocumentServer/cds-ils/files/8059251/moshe-flato-without-accent.txt)

**Comment by salomerohr** [comment]
'-' doesn't work

**Comment by salomerohr** [comment]
Also make the catalogue searchable and results appear in Google.
