### ISSUE TITLE
sanitize user input 

### ISSUE THREAD

**Issue by kpsherva** [CERNDocumentServer/cds-ils#746]
trim trailing spaces from the document/series titles
https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF1991566

**Comment by salomerohr** [comment]
all fields.

**Comment by lydipi** [comment]
An example of a duplicate not detected because of additional spaces: https://catalogue.library.cern/backoffice/series/1d8vw-x7n14
When doing research, both appear: https://catalogue.library.cern/backoffice/series?q=%22Management%20and%20Operations%20Research%20Practices%22&l=list&order=asc&p=1&s=15&sort=bestmatch
