### ISSUE TITLE
Location plan for books

### ISSUE THREAD

**Issue by salomerohr** [CERNDocumentServer/cds-ils#834]
**Is your feature request related to a problem? Please describe.**
Users are a bit lost in the library when trying to find books location based on shelf number:
e.g. Where is 539.12?

**Describe the solution you'd like**
Have a information point next to Shelf number that opens when you click on it: a plan will display the shelf where this shelf number is:
![image](https://github.com/CERNDocumentServer/cds-ils/assets/80258882/20a6b35d-cbc4-46c3-a935-6c8c85ffcabc)

**Additional context**
SCE & SIS can provide the image and matrix.

TASKS:

- [x] export all books with physical item by subject in a csv/excel file
- [ ] discuss the UDP code placement

**Comment by lydipi** [comment]
To avoid the confusion between what we call "shelf" for now (for example 005.8 REB in Salomé's example above) and the shelf number (for example shelf number 1, 2, 3, etc.), we would like to change the name from "Shelf" to "Call number".

**Comment by sakshamarora1** [comment]
Script for updating the shelf locations of all physical items from the provided file: https://gitlab.cern.ch/cds-team/production_scripts/-/merge_requests/20

**Comment by salomerohr** [comment]
I am about to order stickers to add the shelf number on top of each shelf as per the number we gave them in the file, so users can refer to that. @kpsherva could you please let us know how it will be displayed in the catalogue? I see on Sandbox only the Shelf (which will become the Call number) at the moment.

**Comment by salomerohr** [comment]
The map is not loading:


![Image](https://github.com/CERNDocumentServer/cds-ils/assets/80258882/6a18c9c8-9cab-4649-a172-8e04641cdfdc)

**Comment by salomerohr** [comment]
The question mark next to Shelf (which should become Call number) shows: Call number: -
Should it be displaying the Shelf number (how we number the shelves on the map)?

**Comment by kpsherva** [comment]
Sorry, I should have explained the details about maps.
Since the mapping of shelves you've provided is only mapping the production environment, I didn't run the shelf updating script, meaning in order to test the map we need to set the correct shelf number in the edit form. I've updated the document which you were testing, please re-check: https://sandbox-cds-ils.web.cern.ch/backoffice/items/bf1v8-41609

**Comment by lydipi** [comment]
The example is working, thank you for the explanation!

Something very very important: I see that you completely removed the call number (for example 524.8 GRE) in front office and back office, which is problematic for us as already discussed during the meeting a few weeks ago.
This call number is essential for us to locate books. Us, as librarians, will not use the map and the call number is the only way to find exactly the book (i. e. shelf number alone is not enough to find the book directly, otherwise we would have to browse the whole shelf to find it, which is not practical at all).
In addition, all books that are in the depots will not have a map nor a shelf number, so we will not be able to locate easily the books without the call number. Could you please change and put the call number again? with the modification I asked above:
![Capture d’écran 2024-05-14 à 11 28 10 - copie](https://github.com/CERNDocumentServer/cds-ils/assets/148760346/30d80b82-d808-478b-bc31-ad256d36a09e)

To resume, **we need the call number to be visible in front and backoffice** as it is currently the case, and the shelf number should be visible when we hover over the information button in front office.

I maintain my additional comments from above:

- I don't remember talking about two different ways to have access to the localisation? might be a bit confusing for users?
- "Shelf" should be changed to "Call number" (see above)
- The question mark just says "Call number: -" I assume it is for the shelf number, so it should be changed for "Shelf number: 1". In addition I would replace the question mark by an "i" for information.
- For items that are not located in 'CERN Central Library', could you please add an info icon with the text 'Please request online or ask at the Library desk' next to the call number?
- _In addition the embedded map is not needed in back office for documents that are in depots_ : UPDATE -> to avoid to complicate things, you can remove in back office the map as librarians don't need it to find books.

**Comment by kpsherva** [comment]
@lydipi the call number will be still accessible, it will be stored in


![Image](https://github.com/CERNDocumentServer/cds-ils/assets/38131488/b0bef0bd-ac45-4084-8183-7bdd1dcc2d47)


![Image](https://github.com/CERNDocumentServer/cds-ils/assets/38131488/531deb22-3cb7-4901-b3f1-e97ff0e029c5)



I didn't run the script updating all the physical items for the same reason why the shelfs are not updated in the sandbox - because I do not have the mapping for sandbox, we created only the one for production.
Therefore, as it was highlighted before in the meeting, no data will be lost, including the call number. We will leave it displayed aside the shelf.

>"Shelf" should be changed to "Call number" (see above)
The question mark just says "Call number: -" I assume it is for the shelf number, so it should be changed for "Shelf number: 1". In addition I would replace the question mark by an "i" for information.

Apologies for the confusion this caused (see the explanation above). I have updated the https://sandbox-cds-ils.web.cern.ch/literature/e0axn-tqh96 example document accordingly, therefore the labels indicated in the screenshot should now match with the respective data.

In order to make it less confusing for the end user (and quickly findable) we will display the shelf and call number in the "Shelf" column in a following manner:
`01 (524.8 GRE)` 
instead of adding the question mark icon.
I would like to avoid adding additional column for call number to the table because it would visually overload the table (already tested), therefore I think it would be a good compromise to use the parenthesis.

Regarding:
1.
> For items that are not located in 'CERN Central Library', could you please add an info icon with the text 'Please request online or ask at the Library desk' next to the call number?

Do you mean Central Library as in the internal location or CERN Central Library as main location?

2.
> In addition the embedded map is not needed in back office for documents that are in depots : UPDATE -> to avoid to complicate things, you can remove in back office the map as librarians don't need it to find books.

We will remove the map from the backoffice

3. 
> I don't remember talking about two different ways to have access to the localisation? might be a bit confusing for users?

could you explain me what do you mean by two different ways ?

**Comment by salomerohr** [comment]
To discuss this afternoon, but here are already my comments:
1. Central Library as in the internal location (we only mapped that ones). All the items in internal locations Depot 1, 2 and 3, etc. should display 'Please request online or ask at the Library desk' as there is nothing to show on the map and these locations are not accessible to the public.
2. Thanks! Could we also swap, in the backoffice, the Call number (to have it at the top - like it was before) with the Shelf number (it can be where is now displayed the Call number). Librarians will always check with the Call number and do not need the Shelf number as much as users to locate the books.
3. In front office, there is the link to the map on the Shelf number, and the Map on the right under 'Request'.

In front office, if the Call number is displayed in parenthesis after the Shelf number as you said, e.g. 01 (524.8 DAR), fine! At the moment, the Call number only appear in the hover box when the mouse is on the Shelf number. So, that will be changed?

**Comment by salomerohr** [comment]
See comment on other issue related to CERNMap

**Comment by salomerohr** [comment]
Could you please send us a screenshot of how it will look like for books without shelf numbers (e.g. the ones in the Depot)?
