### ISSUE TITLE
Importer: make title insensitive case

### ISSUE THREAD

**Issue by lydipi** [CERNDocumentServer/cds-ils#837]
For example [this document](https://catalogue.library.cern/backoffice/documents/0r92v-28143 ) was not detected as a duplicate of [this one ](https://catalogue.library.cern/backoffice/documents/rnz8f-bn036) when [import preview ](https://catalogue.library.cern/backoffice/importer/task/1337)(on1404062315) was done because of upper case in the title. This greatly increases the risk of duplicate entries in the catalogue.

**Comment by kpsherva** [comment]
Hello @lydipi,
I will resolve this issue since all the title sensitivity issues were fixed and this seems to be a duplicate issue.
In addition, I believe the particular document you've linked was not matched because of differences between edition fields. The matcher rightfully believes that those documents are of different edition, since the field does not match
