### ISSUE TITLE
Openshift: stats not calculated properly

### ISSUE THREAD

**Issue by kprzerwa** [CERNDocumentServer/cds-ils#88]
- [x] fix statistics on books-dev ~(#89)~ (inveniosoftware/invenio-stats#111)
- [ ] enable automatic deployment when tags pushed

Requires #87 (see comment below)

**Comment by equadon** [comment]
Some work have been made to address the stats issue on `books-dev` in https://github.com/CERNDocumentServer/cds-books/pull/89 and in `cds-books-openshift`. However, due to missing #87 we can't test statistics properly since `invenio-stats` returns `null` if not both record view and download stats are working properly.
